name: "cac"

on:
  workflow_dispatch:
  schedule:
    - cron: '10 * * * *'
    - cron: '40 * * * *'

jobs:
  cac:
    uses: invalidunit/check_change/.github/workflows/cac_telegram.yml@main
    secrets:
      _token: ${{ secrets._token }}
      _chap_id: ${{ secrets._chap_id }}

  remove_all_old_actions:
    uses: invalidunit/action/.github/workflows/remove_all_actions.yml@main
